project:
  type: website

execute:
  freeze: auto

website:
  title: "Employee Turnover Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: turnover.qmd
        text: Turnover Details
      - href: survey.qmd
        text: Survey Reponses
      - href: employee-char.qmd
        text: Employee Characteristics
      - href: next-steps.qmd
        text: Next Steps
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/phildwalker/jackson-turnover
          - text: Report a Bug
            href:  https://github.com/phildwalker/jackson-turnover/issues/new


format:
  html:
    theme:
      - brand
    css: styles.css
    toc: true
    # fontcolor: "#333333"
    linkcolor: "#007bff"



