project:
  type: website

execute:
  freeze: auto

website:
  title: "Employee Turnover Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Turnover Landscape
        menu: 
        - href: turnover.qmd
          text: Turnover Details
        - href: survey.qmd
          text: Survey Reponses
        - href: employee-char.qmd
          text: Employee Characteristics
      - text: Policy Cost Estimation
        href: policy-cost.qmd
      - text: Policy Impact
        menu:
        - href: impact.qmd
          text: Projected Impact
        - href: next-steps.qmd
          text: Next Steps
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/phildwalker/jackson-turnover
          - text: Report a Bug
            href:  https://github.com/phildwalker/jackson-turnover/issues/new


format:
  html:
    theme:
      - brand
    css: styles.css
    toc: true
    # fontcolor: "#333333"
    linkcolor: "#5a2158"



