---
title: "Overview"
format:
  html:
    title-block-banner: false # or none
---

::: {.callout-note collapse="false"}
# Note from Phil

```{r}
#| echo: false
dt <- Sys.Date()
print(glue::glue("Presentation last built on: {dt}"))
```

I am aiming to provide a clear and instructive analysis to Sr Leadership, mixing both written prose and visuals to provide an artifact for later viewing as well as a tool to center the conversation for this decision. I will start with the high level recommendation and then provide the steps for how we get there, knowing that depending on the leader's availability, sometimes there is only time for the analysis and sometimes it's desired to know how we got to the answer.

I have intentionally designed this to be a code driven analysis in order to ensure that both the analysis is **reproducible** as well as that the code is **reusable**. It has been a common occurance for me where I have provided an analysis, we've made a decision and then a year later we want to evaluate the results. By this solution being code based, we are able to quickly recreate the analysis and update with the necessary data without having to wonder if some data was omited due to outliers or if we intentionally just focused on a specific population.

Because this presentation is meant for Sr Leadership I have intentionally removed most code, except for situations where it would be instructive or the detailed appendix. If you would like to review the code, please visit the code repository on Github by clicking on the icon on the top right and navigating to the "Source Code" link.

Thanks for joining as we analyze the turnover data!

-phil walker

:::


# Analysis Overview

::: panel-tabset
## Problem Statement:

Below is the provided problem statement. This is what we will use as our driving focus for this analysis.

> You are a Senior HR Data & Insights Consultant and have been asked to assist senior HR leadership make a decision regarding a planned policy change.

> 1.  Senior leadership is concerned with the on-going impact the pandemic and “Great Resignation” has had on the workforce. There is a pervasive belief that turnover has been steadily on the rise over the past five years, and recent high-profile terminations among some of the organization’s top performers have raised questions regarding the organization’s retention strategy.
> 2.  Senior leaders believe compensation is driving turnover and have proposed implementing an across the board annual raise of 6% at the start of next year to counteract the effect of inflation.
> 3.  You have one week to clean, review, and analyze the provided data to help senior leadership understand the current turnover landscape, the cost of their proposal, and whether the proposed retention strategy will have the desired impact.

## Outcomes

The following are the outcomes of this analysis. Also provided are the links to the locations of the outcomes.

-   **What's the turnover picture?**
    -   *tdlr;* 2022 and 2023 saw significantly higher turnover, but it's been returning back to pre-pandemic rates.
    -   Detailing the current turnover rate -\> [Turnover Analysis](turnover.qmd#exit-trend)
-   **What's driving exits?**
    -   Are the survey responses correlated to employee exits?
        -   *tdlr;* there was a shift in reponses from 2021 to 2023 + 2025
        -   Details in survey reponses -\> [Survey Analysis](survey.qmd#overall-response)
    -   Are their certain employee characteristics that are more likely to exit?
        -   *tldr;* it's more likely that ----
        -   Details of employees -\> [Employee Characteristics](employee-char.qmd#overall-response)
-   **What's the cost to implement this proposed policy?**
    -   *tldr;* The projected cost would be between $11.6M - $13M 
    -   Details of policy cost -\> [Policy Cost](policy-cost.qmd)   
    -   Project policy impact -\> [Policy Impact](impact.qmd)   

-   **Where to now?**
    -   [Next Steps](next-steps.qmd)
    -   Suggestions for additional data to capture
    -   Questions for further discussion

## Data Soures

For this analysis we will be using the following data sources:

-   HRIS Data - Employee tenure and Demographics
    -   Provided by employeer
-   HRIS Data - Employee Survey Response
    -   Provided by employeer
-   [BLS - JOLTS](https://www.bls.gov/jlt/)
    - filtered down to Finance and Insurance category -> looks at nationwide rates
-   [~~BLA - Inflation (Consumer Price Index)~~](https://www.bls.gov/cpi/)
-   [~~Michigan Job~~](https://www.milmi.org/)
-   [~~Michigan Workforce Reports~~](https://www.michigan.gov/mdcs/quick-links/workforcereports)
-   [~~Nashville Workforce Reports~~](https://www.bls.gov/eag/eag.tn_nashville_msa.htm)

## Assumptions

- Terminology
    * I am equating exits = terminations = turnover  = quits = separation
    * I know that the BLS distinquishes between layoffs/ terminations (involuntary) and quits (voluntary)

-   Calculations
    -   Average Employees Per Month: Uses the \# at the start of the month
    -   Turnover = \# Resigned/ Avg Employee

-   For this analysis we are also going to remove Temporary employees.

-   We recognize that there have been a large economic shift where more employees are staying at their companies, if we were to make a policy change we would want to differentiate between (and look for a causal link) between the policy and the company's turnover.

-   Identify top performers as:

    -   those with a performance rating of 4 or 5

-   Assuming that employees that are that employees with the effective date of the current job are \_\_\_\_\_

-   Jackson's NAICS code is 524113 (designates Direct Life Insurance Carriers)
    -   falls under the "Finance and Insurance" sector. (Sector 52)
    
:::