---
title: "Next Steps"
---

So what are our next steps from here?


# Additonal Information to Capture 

I would love to capture more information about exits to better our understanding of the drivers in this area.
1.  It would be interesting is capturing when we have 'regrettable loss' (beyond a voluntary termination), or better detailing what characteristics would make an exit more regettable for the organization.
1. Would be interesting to bring in the exit interview data to augment the analysis to dig further into employee's decisions to leave. 
1. For our employee enagement survey, it would be helpful to think about gathering more detailed feedback around employee perceptions. (ie something like: "are you fairly compensated for the work you perform?", with the goal of understanding how an across the board raise might impact their perceptions).


# Testing Hypotheses

1. We would want to measure the turnover after we make this policy change to determine if it had the intended affect.
    * Know that this would be a long feedback loop as we would want to wait at least a month before testing again.


# Other considerations

1. The peaks in 2022 and 2023 likely also have a company policy connected to them, especially for the involuntary turnovers. While this is harder to store, capturing this business decision in a structured format would be helpful for future analyses.